"""Adicionado Usuario e relecionamentos

Revision ID: 9f81d16147ba
Revises: 6b45233f0d1a
Create Date: 2025-01-07 21:43:33.236417

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9f81d16147ba'
down_revision: Union[str, None] = '6b45233f0d1a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
